config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'weather/new'
  post 'weather/create'

  # Defines the root path route ("/")
  root to: 'weather#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def new; end

  def create
    @weather_result = Services::Weather::CachedWeatherForecastService.new(location: params[:location]).forecast

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href="#!">Weather App</a>
        </div>
    </nav>

    <%= yield %>

    <!-- Footer-->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <%# <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#!">About</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Contact</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                    </ul> %>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; Adam Zolo 2024. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item me-4">
                            <a href="https://www.linkedin.com/in/adamzolotarev/" target="_blank" rel="noopener noreferrer"><i class="bi-linkedin fs-3"></i></a>
                        </li>
                        <li class="list-inline-item me-4">
                            <a href="https://blog.adamzolo.com" target="_blank" rel="noopener noreferrer"><i class="bi bi-globe">Personal Blog</i></a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/weather/create.turbo_stream.erb
<%= turbo_stream.replace :weather_turbo_frame do %>
  <%= turbo_frame_tag :weather_turbo_frame do %>
    <% if @weather_result.error? %>
      <div class="row">
        <div class="col">
          <h2><%= @weather_result.payload %></h2>
        </div>
      </div>
    <% else %>
      <% forecast_data = @weather_result.payload %>
      <% if forecast_data[:cache_expires_in_mins] %>
        <div class="row">
          <p class="fs-6"><%= "Data can be up to #{forecast_data[:cache_expires_in_mins]} minutes old" %></p>
        </div>
      <% end %>
      <hr/>
      <div class="row">
        <div class="col">
          <h2>Forecast</h2>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <h2>Current temperature: <%= forecast_data[:current_temp] %></h2>
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="col">
          <h2>Forecast</h2>
        </div>
      </div>
      <% forecast_data[:days_forecast].each do |days_forecast| %>
        <div class="row">
          <div class="col">
            Date
          </div>
          <div class="col">
            <%= days_forecast[:date] %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            Temp Min
          </div>
          <div class="col">
            <%= days_forecast[:min_temp] %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            Temp Max
          </div>
          <div class="col">
            <%= days_forecast[:max_temp] %>
          </div>
        </div>
        <div class="row">
          <div class="col">
            Conditions
          </div>
          <div class="col">
            <%= days_forecast[:conditions] %>
          </div>
        </div>
        <hr/>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/weather/new.html.erb
<header class="masthead">
  <div class="container position-relative">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="text-center text-white">
          <!-- Page heading-->
          <h1 class="mb-5">Enter the address, get the forecast!</h1>
          <%= form_with url: weather_create_path,
                        class: 'form-inline' do |form| %>
            <div class="row">
              <div class="col">
                <%= form.text_field :location,
                                class: 'form-control form-control-lg',
                                placeholder: '1234 street, Columbus, Ohio 43016' %>
              </div>
              <div class="col-auto">
                <%= form.submit 'Forecast', class: 'btn btn-primary btn-lg' %>
              </div>
            </div>
          <% end %>
          <br>
          <%= turbo_frame_tag :weather_turbo_frame %>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Testimonials-->
<section class="testimonials text-center bg-light">
  <div class="container">
    <h2 class="mb-5">What people are saying...</h2>
    <div class="row">
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag "testimonials-1.jpg", class: 'img-fluid rounded-circle mb-3' %>
          <h5>Margaret E.</h5>
          <p class="font-weight-light mb-0">"This is fantastic! I love this weather app!"</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag "testimonials-2.jpg", class: 'img-fluid rounded-circle mb-3' %>
          <h5>Fred S.</h5>
          <p class="font-weight-light mb-0">"Weather app is amazing. I've been using it to create lots of forecasts."</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
          <%= image_tag "testimonials-3.jpg", class: 'img-fluid rounded-circle mb-3' %>
          <h5>Sarah W.</h5>
          <p class="font-weight-light mb-0">"Thanks so much for making this weather app available to us!"</p>
        </div>
      </div>
    </div>
  </div>
</section>